@extends('layouts.app', ['title' => 'Dashboard | Cris Barber Shop'])
@section('content')
<main class="page"><section class="dashboard">
<header class="topbar"><div><div class="brand">Cris Barber Shop</div><h1>{{ ucfirst($user->role) }} dashboard</h1><p class="muted">Welcome, {{ $user->name }}.</p></div><div><a class="button" href="{{ $user->role === 'admin' ? route('accounts.create') : '#' }}">{{ $user->role === 'admin' ? 'Add barber' : 'My workspace' }}</a> <form class="inline" method="POST" action="{{ route('logout') }}">@csrf <button>Log out</button></form></div></header>
@if(session('status'))<p class="alert">{{ session('status') }}</p>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
@if($user->role === 'admin')
<div class="stats"><article class="stat"><span class="muted">Today’s sales</span><strong>₱{{ number_format($todayRevenue,2) }}</strong></article><article class="stat"><span class="muted">This month’s sales</span><strong>₱{{ number_format($monthRevenue,2) }}</strong></article><article class="stat"><span class="muted">Shop share this month</span><strong>₱{{ number_format($monthShopShare,2) }}</strong></article><article class="stat"><span class="muted">Pending GCash</span><strong>{{ $pendingPayments }}</strong></article></div>
<div class="grid"><section class="panel"><h2>Record completed service</h2><form method="POST" action="{{ route('transactions.store') }}">@csrf <label>Barber</label><select name="barber_id" required>@foreach($barbers->where('status','active') as $barber)<option value="{{ $barber->id }}">{{ $barber->name ?? $barber->first_name.' '.$barber->last_name }}</option>@endforeach</select><label>Service</label><select name="service_id" required>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }} — ₱{{ number_format($service->price,2) }}</option>@endforeach</select><label>Payment</label><select name="payment_method"><option value="cash">Cash</option><option value="gcash">GCash</option></select><label>GCash reference (if applicable)</label><input name="gcash_reference_no"><div class="actions"><button>Save transaction</button></div></form></section>
<section class="panel"><h2>Add service</h2><form method="POST" action="{{ route('services.store') }}">@csrf <label>Name</label><input name="name" required><label>Price</label><input name="price" type="number" step="0.01" min="0" required><label>Duration (minutes)</label><input name="duration_minutes" type="number" min="5" value="30" required><label>Description</label><input name="description"><div class="actions"><button>Add service</button></div></form></section></div>
<section class="panel"><h2>Team</h2><table><thead><tr><th>Barber</th><th>Email</th><th>Status</th></tr></thead><tbody>@forelse($barbers as $barber)<tr><td>{{ $barber->name ?? $barber->first_name.' '.$barber->last_name }}</td><td>{{ $barber->email }}</td><td><form class="inline" method="POST" action="{{ route('barbers.status',$barber->id) }}">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()"><option value="active" @selected($barber->status==='active')>Active</option><option value="inactive" @selected($barber->status==='inactive')>Inactive</option><option value="on_leave" @selected($barber->status==='on_leave')>On leave</option></select></form></td></tr>@empty<tr><td colspan="3">No barber accounts yet.</td></tr>@endforelse</tbody></table></section>
@else
<div class="stats"><article class="stat"><span class="muted">Your earnings today</span><strong>₱{{ number_format($todayEarnings,2) }}</strong></article><article class="stat"><span class="muted">Your earnings this month</span><strong>₱{{ number_format($monthEarnings,2) }}</strong></article><article class="stat"><span class="muted">Earnings rule</span><strong>50%</strong><p class="muted">Your share is calculated automatically for every completed service.</p></article></div>
<section class="panel"><h2>Log completed service</h2><form class="quick-form" method="POST" action="{{ route('transactions.store') }}">@csrf <div><label>Service</label><select name="service_id" required>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }} — ₱{{ number_format($service->price,2) }}</option>@endforeach</select></div><div><label>Payment</label><select name="payment_method"><option value="cash">Cash</option><option value="gcash">GCash</option></select></div><div><label>GCash reference</label><input name="gcash_reference_no"></div><div class="actions"><button>Record service</button></div></form></section>
@endif
<section class="panel"><h2>Recent transactions</h2><table><thead><tr><th>Date</th><th>Barber</th><th>Amount</th><th>Barber share</th><th>Payment</th><th>Status</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr><td>{{ \Carbon\Carbon::parse($transaction->created_at)->format('M d, g:i A') }}</td><td>{{ $transaction->barber_name }}</td><td>₱{{ number_format($transaction->total_amount,2) }}</td><td>₱{{ number_format($transaction->barber_share,2) }}</td><td>{{ strtoupper($transaction->payment_method) }}</td><td>{{ ucfirst($transaction->verification_status) }} @if($user->role==='admin' && $transaction->verification_status==='pending')<form class="inline" method="POST" action="{{ route('payments.verify',$transaction->payment_id) }}">@csrf <input type="hidden" name="status" value="verified"><button>Verify</button></form>@endif</td></tr>@empty<tr><td colspan="6">No transactions recorded yet.</td></tr>@endforelse</tbody></table></section>
@if($user->role==='admin')<section class="panel"><h2>Service menu</h2><table><thead><tr><th>Service</th><th>Price</th><th>Duration</th><th></th></tr></thead><tbody>@forelse($services as $service)<tr><td>{{ $service->name }}</td><td>₱{{ number_format($service->price,2) }}</td><td>{{ $service->duration_minutes }} min</td><td><form method="POST" action="{{ route('services.destroy',$service->id) }}">@csrf @method('DELETE')<button>Remove</button></form></td></tr>@empty<tr><td colspan="4">Add your first service above.</td></tr>@endforelse</tbody></table></section>@endif
</section></main>
@endsection
