<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class DashboardController extends Controller {
 public function __invoke(Request $request) { $user=$request->user(); $services=DB::table('services')->orderBy('name')->get();
  if($user->role==='barber') { $barber=DB::table('barbers')->where('user_id',$user->id)->first(); abort_unless($barber,403); return view('dashboard',compact('user','services','barber')+['transactions'=>$this->transactions()->where('transactions.barber_id',$barber->id)->limit(12)->get(),'todayEarnings'=>DB::table('transactions')->where('barber_id',$barber->id)->whereDate('created_at',today())->sum('barber_share'),'monthEarnings'=>DB::table('transactions')->where('barber_id',$barber->id)->whereBetween('created_at',[now()->startOfMonth(),now()->endOfMonth()])->sum('barber_share')]); }
  abort_unless($user->role==='admin',403); $month=[now()->startOfMonth(),now()->endOfMonth()]; return view('dashboard',compact('user','services')+['barbers'=>DB::table('barbers')->leftJoin('users','barbers.user_id','=','users.id')->select('barbers.*','users.name','users.email')->orderBy('first_name')->get(),'transactions'=>$this->transactions()->limit(12)->get(),'todayRevenue'=>DB::table('transactions')->whereDate('created_at',today())->sum('total_amount'),'monthRevenue'=>DB::table('transactions')->whereBetween('created_at',$month)->sum('total_amount'),'monthShopShare'=>DB::table('transactions')->whereBetween('created_at',$month)->sum('shop_share'),'pendingPayments'=>DB::table('payments')->where('verification_status','pending')->count()]); }
 private function transactions() { return DB::table('transactions')->join('barbers','transactions.barber_id','=','barbers.id')->leftJoin('users','barbers.user_id','=','users.id')->leftJoin('payments','payments.transaction_id','=','transactions.id')->select('transactions.*',DB::raw("COALESCE(users.name, barbers.first_name || ' ' || barbers.last_name) as barber_name"),'payments.payment_method','payments.verification_status','payments.gcash_reference_no','payments.id as payment_id')->orderByDesc('transactions.created_at'); }
}
